apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-pod
  labels:
    project: kubernetes-project
spec:
  containers:
  - name: kubernetes-pod
    image: karllchris/educative-deploy-project
    ports:
    - containerPort: 31111